// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package server

import (
	"context"

	"github.com/uyuyuuy/go-zero-shop-rpc/app/cart/internal/logic"
	"github.com/uyuyuuy/go-zero-shop-rpc/app/cart/internal/svc"
	"github.com/uyuyuuy/go-zero-shop-rpc/app/cart/pb"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) CartList(ctx context.Context, in *pb.CartListReq) (*pb.CartListResp, error) {
	l := logic.NewCartListLogic(ctx, s.svcCtx)
	return l.CartList(in)
}

func (s *CartServer) AddCart(ctx context.Context, in *pb.AddCartReq) (*pb.AddCartResp, error) {
	l := logic.NewAddCartLogic(ctx, s.svcCtx)
	return l.AddCart(in)
}

func (s *CartServer) UpdateCart(ctx context.Context, in *pb.UpdateCartReq) (*pb.UpdateCartResp, error) {
	l := logic.NewUpdateCartLogic(ctx, s.svcCtx)
	return l.UpdateCart(in)
}

func (s *CartServer) DelCart(ctx context.Context, in *pb.DelCartReq) (*pb.DelCartResp, error) {
	l := logic.NewDelCartLogic(ctx, s.svcCtx)
	return l.DelCart(in)
}
